title = "Evan Relf"
base_url = "/"
compile_sass = true
minify_html = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "Tomorrow"
render_emoji = true

[link_checker]
skip_prefixes = [
  "https://linkedin.com"
]

[extra]
